### ISSUE TITLE
创建项目基础代码

### ISSUE THREAD

**Issue by limingth** [limingth/xinsanban#2]
提交3次代码，分别完成以下三个功能：
1. user-boilerplate 的会员功能，支持 user, member, admin 三级用户管理体系
2. 加入 summernote-posts 那个包，实现文章功能，可以通过 summernote 编辑较为复杂的文章
3. 实现一个 xinsanban.maodou.io 首页功能，做一个 landing page，包含4个sections
  - 协会介绍
  - 协会新闻
  - 协会图片
  - 联系我们

先打好框架，参考腾飞官网首页的 landing page，内容待定

**Comment by roy2020china** [comment]
updates
1. 加入 summernote-posts 那个包之后，跑起来了，再加入“点赞”，“评论”那两个包
2. Landing page 做三四个导航菜单，比如 “新闻”，“联系我们”等。
