### ISSUE TITLE
和戴老师沟通的记录

### ISSUE THREAD

**Issue by roy2020china** [limingth/xinsanban#4]
时间：0706 14：00
地点：清华科技园 X-LAB
参加人：
X-LAB-戴老师
毛豆网-陈晓晓，张冰

未经当事人校阅，如有错漏，请补充、更正。

	1. 开发该微信公众号的初衷
		a. 初期没有多少用户，希望更多的用户关注这个号，吸粉
		b. 估计1000-2000，1-2万用户轻轻松松没有问题。
		c. 做网站所需要的文案材料，戴老师那边也在准备。随时沟通
		d. 基本需求：
			i. 最初：我们只是单向推送消息，只是一个展示性的网站。
			ii. 有一些活动模块可以让用户报名即可。
		e. 具体需求
			i. 底栏三个菜单，分别是：
				1) 新闻
					a) 新闻：过往的活动。静态的信息
					b) 新闻/研究发布/报告。三个二级子菜单：
						i) 政策研究报告
						ii) 市场研究报告
						iii) 行业研究报告（新三板里面的企业）
					c) 每个二级子菜单：
							One. 可以是单独的H5页面，是文章的呈现
							Two. 文意的内容：
								First. 标题
								Second. 作者
								Third. 时间
								Fourth. 摘要
								Fifth. 具体的内容
				2) 活动.
					a) 比如，每季度的论坛可以作为活动来发布。
					b) 目前只要2个二级菜单
						i) 往期活动
						ii) 最新活动
						iii) 也可以直接跳转到一个单独的H5页面
					c) 以后会1个二级菜单
						i) 增加调研
					d) 活动主要是：活动报名，推导。可以直接调用毛豆网之前为大赛开发的模块
						i) 报名模块要求用户填写
							One. 姓名
							Two. 联系方式
							Three. 工作单位
							Four. 关注点：
				3) 关于我们/实验室介绍/新三板研究室（和DNA完全不同）
	2. 请毛豆网代为申请公众号。具体需要什么材料，由陈晓晓沟通联系

![webwxgetmsgimg](https://cloud.githubusercontent.com/assets/10363512/16611367/695499ee-4393-11e6-8ede-dd79eb5dcb90.jpg)

**Comment by limingth** [comment]
这个项目需求，几乎就是我们 mSaaS + posts (新闻) + activities (活动) 的结构，完全可以复用之前的代码，@roy2020china 之前对mSaaS的学习，正好可以派上用处了。

**Comment by roy2020china** [comment]
1. 我会再看一下mSaaS。
 2. 今天先做墨刀原型。
 3. 晚上，不忙的时候，贾天会帮我帮UBUNTU - 赵老师意见是 我以后主要还是在本地跑Meteor. 今天晚上装UBUNTU。
